### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ssbarnea** [markelliot/update-yarn-deps#1]
Sorry to use the issue tracker for this bug I have few important questions:

- does it support the v2 lock file format? -- new as in... introduced two years ago
- does it support skipping some specific dependencies?

**Comment by markelliot** [comment]
Lock file format: this upgrader assumes yarn2 but makes no additional assumptions about the lock file produced by yarn2. 

Skipping deps: no, the semantics are governed entirely by what would happen if you ran [`yarn up ‘*’`](https://yarnpkg.com/cli/up), and I wouldn’t be open to pull requests that change this behavior.
